# Site settings
title: Portfolio Aldo Junior Bornacelly Navarro
description: My portfolio.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aldo Junior Bornacelly Navarro
user_description: Soy una marca innovadora que se dedica a crear soluciones tecnológicas únicas y emocionantes para mejorar la vida de las personas. Mi enfoque se centra en brindar experiencias de usuario excepcionales a través de aplicaciones web y móviles de alta calidad. Mi marca cuenta con una sólida formación en desarrollo de software, en particular en el desarrollo web full-stack. Además, cuento con experiencia en entornos de desarrollo ágil, colaborando con equipos interfuncionales. 
user_title: Estudiante de ingeniería de sistemas.
email: bornacelinavarro@gmail.com
twitter_username: lorem_ipsum
github_username:  ajbornacellyn
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
